waypoint_planner:
  ros__parameters:
    waypoint_graph_file: '/root/mfa_ws/waypoint_graph.pkl'
    
    # Topics
    uav_gps_topic: '/mavros/global_position/global'
    uav_altitude_amsl_topic: '/mavros/altitude'
    uav_altitude_rel_topic: '/mavros/global_position/rel_alt'    
    goal_topic: 'waypoint_request'
    waypoint_response_topic: 'waypoint_response'
    setpoint_topic: '/mavros/setpoint_raw/global'
    state_topic: '~/state'
    
    # Takeoff
    use_takeoff_pos: true    
    takeoff_altitude: 20.0 # relative to takeoff height
    takeoff_latitude: 40.0 # used if use_takeoff_pos is false
    takeoff_longitude: -74.0 # used if use_takeoff_pos is false
    
    # FSM
    fsm_rate: 20.0
    altitude_threshold: 0.2
    position_threshold: 2.0

waypoint_gui:
  ros__parameters:
    satellite_map_file: '/root/mfa_ws/satellite_map.pkl'
